POST  http://localhost:3333/events
Content-Type: application/json

{
    "title": 123,
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/65577833-76db-4363-b9a8-542990b0efc6/attendees
Content-Type: application/json

{
  "name": "Franklin Marden",
  "email": "rodrigues2_marden@hotmail.com"
}

###

GET http://localhost:3333/events/65577833-76db-4363-b9a8-542990b0efc6

###

GET http://localhost:3333/attendees/5/badge

###
GET http://localhost:3333/attendees/5/check-in

###

GET http://localhost:3333/events/65577833-76db-4363-b9a8-542990b0efc6/attendees?query=franklin